apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-event-handler-json
data:
  hooks.json: |-
    [
      {
        "id": "{{ .Values.id }}",
        "execute-command": "{{ .Values.executecommand }}",
        "command-working-directory": "{{ .Values.commandworkingdirectory }}"
      }
    ]
