# Default values for alert-event-handler.
# This is a YAML-formatted file.

# Configure ConfigMap content
hookid: command
executecommand: /etc/webhook/command.sh
commandworkingdirectory: /var/webhook
