# Configure ConfigMap Content
# hooks.json Values
id: "commands"
executecommand: "/var/scripts/hook1.sh"
commandworkingdirectory: "/var/scripts/"

# Executed Shell Commands
commands: |-
  #!/bin/sh
  echo ""
  echo "--- EVENT START ---"
  echo "`date`"
  echo "Your first command"
  oc version
  echo "`date`"
  echo "--- EVENT ENDE ---"