# Configure ConfigMap Content
# Alert-Event-Handler Version
image:
  repository: 29041966/alert-event-handler
  tag: 0.1.3

# hooks.json Values
id: "commands"
executecommand: "/var/scripts/hook1.sh"
commandworkingdirectory: "/var/scripts/"

# Executed Shell Commands
commands: |-
  #!/bin/sh
  echo ""
  echo "--- EVENT START ---"
  echo "`date`"
  echo "Your first command"
  oc version
  echo "`date`"
  echo "--- EVENT ENDE ---"