# Default values for alert-event-handler.
# This is a YAML-formatted file.

# Configure ConfigMap content
hook-id: command
execute-command: /etc/webhook/command.sh
command-working-directory: /var/webhook
