apiVersion: v1
entries:
  alert-event-handler:
  - apiVersion: v2
    appVersion: 0.1.7
    created: "2020-09-04T22:18:42.827520354+02:00"
    description: Alert-Event-Hangler for Prometheus and Grafana
    digest: 034263142f38fff008ccf6c099101c32966a6b6582adc13a6141add5ab860dd9
    name: alert-event-handler
    type: application
    urls:
    - https://m-gnaedig.github.io/alert-event-handler/helm/alert-event-handler-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 0.1.6
    created: "2020-09-04T22:18:42.827310841+02:00"
    description: Alert-Event-Hangler for Prometheus and Grafana
    digest: 6de235074a3027e61d493f388c1bd43fc2440e1ba9b168ca1e0f5883963c7d9a
    name: alert-event-handler
    type: application
    urls:
    - https://m-gnaedig.github.io/alert-event-handler/helm/alert-event-handler-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 0.1.5
    created: "2020-09-04T22:18:42.827129431+02:00"
    description: A Helm chart for Grafana and Prometheus Alert-Event-Hangler
    digest: 9b1c2390d1adc44e049ea40486d642aab4012ae1e27f8a64f4e7022ebff2868e
    name: alert-event-handler
    type: application
    urls:
    - https://m-gnaedig.github.io/alert-event-handler/helm/alert-event-handler-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 0.1.4
    created: "2020-09-04T22:18:42.826917264+02:00"
    description: A Helm chart for Kubernetes
    digest: e8f3b4c24812f3d7f177a3b866c39ef2dfdcf1e276c1e54fe2ddc3e68b016494
    name: alert-event-handler
    type: application
    urls:
    - https://m-gnaedig.github.io/alert-event-handler/helm/alert-event-handler-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2020-09-04T22:18:42.826347788+02:00"
    description: A Helm chart for Kubernetes
    digest: 31accdaf79e97b124bcaec7bbef3dbf232d03a1ef37799a9c93181e3ebabc7de
    name: alert-event-handler
    type: application
    urls:
    - https://m-gnaedig.github.io/alert-event-handler/helm/alert-event-handler-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2020-09-04T22:18:42.825710921+02:00"
    description: A Helm chart for Kubernetes
    digest: a81e68591ea380bd30891374091acafd8c0ecc753a8695a25439844bcad44373
    name: alert-event-handler
    type: application
    urls:
    - https://m-gnaedig.github.io/alert-event-handler/helm/alert-event-handler-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2020-09-04T22:18:42.82550825+02:00"
    description: A Helm chart for Kubernetes
    digest: 22ca8647052fb82a41b5101636fbc67506ae71b5d624f36438ce0a3dd0841888
    name: alert-event-handler
    type: application
    urls:
    - https://m-gnaedig.github.io/alert-event-handler/helm/alert-event-handler-0.1.1.tgz
    version: 0.1.1
generated: "2020-09-04T22:18:42.825188546+02:00"
